version: 1.0
telegram:
  token: ""  # 机器人TOKEN
  botPassword: "0000" # 模式一密码

vpn:
  chromePath: ./Chrome  # 谷歌浏览器可执行文件路径
  ip: 127.0.0.1
  port: 9527
  retry: 20  # 最大重试次数
  urlList:
    [
      {
        name: '',
        url: '',
      },
    ]
    
vpn2:
  retry: 20
  urlList:
    [
      {
        name: '猪猪侠',
        url: 'https://zhuzhuxia.cloud'
      }
    ]

webdav:
  uploadPath: /Surfboard/profiles/  # webdav路径
  savePath: files/  # 文件保存路径
  options:
    webdav_hostname: ""  # webdav地址
    webdav_login: ""  # 账号
    webdav_password: ""  # 密码
    disable_check: True


public:
  mode: "surfboard"
  format: ".conf"
  subconverterPath: subconverter/subconverter