version: 1.0
telegram:
  token: ""  # 机器人TOKEN
  botPassword: "0000" # 模式一密码

vpn:
  chromePath: ./Chrome  # 谷歌浏览器可执行文件路径
  ip: 127.0.0.1
  port: 9527
  retry: 20  # 最大重试次数
  savePath: ./
  urlList:
    [
      {
        name: '冲浪猫',
        url: 'https://msclm.xyz',
      },
    ]
    
vpn2:
  retry: 20
  urlList:
    [
      {
        name: '五元店',
        url: 'https://www.wuyuandianpu.com'
      }
    ]

webdav:
  uploadPath: /Surfboard/profiles/  # webdav路径
  savePath: ./urls/  # 文件保存路径
  options:
    webdav_hostname: ""  # webdav地址
    webdav_login: ""  # 账号
    webdav_password: ""  # 密码
    disable_check: True


public:
  mode: "surfbrand"
  format: ".conf"